### ISSUE TITLE
Android Support

### ISSUE THREAD

**Issue by brnwlshubh** [chanderlud/giga-grabber#1]
Can you add support for android.

**Comment by chanderlud** [comment]
If/when Iced has stable android support, this is something that could be pursued. Refer to this issue https://github.com/iced-rs/iced/issues/302

**Comment by brnwlshubh** [comment]
@chanderlud Is the support available to use?

**Comment by chanderlud** [comment]
I do not think Iced will ever have Android support. Giga Grabber's backend could be modified for use with another frontend (Flutter, Kotlin, etc) that would support Android, but I am not super interested in doing that myself.
