### ISSUE TITLE
UI is flickering and not working, unable to import proxies and unable to use it

### ISSUE THREAD

**Issue by Indratejreddy** [chanderlud/giga-grabber#5]
I am not a Rust dev but when I cloned and built and run it, the UI was flickering and not letting me to import the proxies

![image](https://github.com/chanderlud/giga-grabber/assets/66834653/b7411381-7c0e-4c94-b7ad-5f2aaade9e9f)

**Comment by chanderlud** [comment]
Hi, I think this issue is with Iced which Giga Grabber uses for its GUI. Are you getting any messages in the console if you run it in debug mode?

**Comment by Indratejreddy** [comment]
I can see the UI loading but when I choose file for proxies it is not loading and screen is flickering

**Comment by Indratejreddy** [comment]
https://uploadnow.io/f/h7LfN8C

**Comment by chanderlud** [comment]
That's pretty weird, you may want to open an issue on the Iced repository for that. You can manually edit the config file to add your proxies

**Comment by Indratejreddy** [comment]
@chanderlud Could you please tell me where I should keep the Mega Drive URL?
![image](https://github.com/chanderlud/giga-grabber/assets/66834653/a57c5a7f-edb2-4492-b119-bd1e800b2158)

**Comment by chanderlud** [comment]
You can enter the URL to your mega folder in the user interface

**Comment by Indratejreddy** [comment]
import is not working I tried, UI is not that great at all please show me where to put the url?

**Comment by chanderlud** [comment]
![image](https://github.com/chanderlud/giga-grabber/assets/109788326/7fd60a72-9f5d-49d8-b79a-980497106c93)

If you feel that there are UI/UX issues, I would appreciate your contribution of fixes for these issues.

**Comment by Indratejreddy** [comment]
I want to but unforunately I am not a rust developer
